network_id: meshmon-public-network
node_config:
  - node_id: ripple
    poll_rate: 30
    retry: 2
    url: https://meshmon.ripplefcl.com
  - node_id: will-lab-cloud
    poll_rate: 30
    retry: 2
    url: https://meshmon.mcda.dev
  - node_id: will-lab-home
    poll_rate: 30
    retry: 2
    url: http://wan0.mcda.dev:8000

node_version:
  - ">=3.1.0"
  - "<4.0.0"
