network_id: meshmon-public-network
node_config:
  - node_id: ripple
    poll_rate: 30
    retry: 2
    url: https://meshmon.ripplefcl.com
  - node_id: will-lab-ovh
    poll_rate: 30
    retry: 2
    url: http://51.195.226.54:8000
  - node_id: will-lab-home
    poll_rate: 30
    retry: 2
    url: https://meshmon.mcda.dev

node_version:
  - ">=3.1.0"
  - "<4.0.0"
